version: '3.8'

services:
  tos_website:
    build:
      context: .
      dockerfile: WebsiteDockerfile
    develop:
      watch:
        - action: sync
          path: ./../Website/
          target: /var/www/html
          ignore:
            - Website/node_modules
            - Website/composer
            - .git
    ports:
      - "127.0.0.3:80:80"
      - "127.0.0.3:9003:9003"
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - ./../Website/:/var/www/html
    depends_on:
      - mariadb

  tos_backend:
    build:
      context: .
      dockerfile: BackendDockerfile
    develop:
      watch:
        - action: sync
          path: ./../GameBackend/
          target: /var/www/html
          ignore:
            - GameBackend/node_modules
            - GameBackend/composer
            - .git
    ports:
      - "127.0.0.4:80:80"
      - "127.0.0.4:9003:9003"
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - ./../GameBackend/:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  tos_chat_server:
    build:
      context: .
      dockerfile: ChatServerDockerfile
    develop:
      watch:
        - action: sync
          path: ./../ChatServer/
          target: /var/chat_server
          ignore:
            - .git
    ports:
      - "127.0.0.5:12345:12345"
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - ./../ChatServer/:/var/chat_server
    depends_on:
      - mariadb

volumes:
  esdata:
